### ISSUE TITLE
How does this solve the issues that mawie81/electron-oauth2 had?

### ISSUE THREAD

**Issue by AlexCatch** [kanekotic/oauth-electron#4]
Another oauth2 library for handling the oauth flow for Electron was https://github.com/mawie81/electron-oauth2

It was archived by the author as it wasn't safe for use in production because it stored the secret key client side - meaning that anyone could uncompress the `.asar` in production & grab it.

I do see the examples include a `secret` property in the info passed to the `oauth2` function so I'm unsure if I'm just missing something or this library faces the same issue as the ones linked.

@aguynamedben is this something you could possibly chime in on? Considering your research when looking at `mawie81/electron-oauth2`

**Comment by alvarolorentedev** [comment]
hello @AlexCatch thanks for writing.

There is a difference in the lines that this library just takes care of the process of authorization with oauth and how events work in electron. Secret management is responsibility of the final application.

The idea of the library is that you can pass either the main window or a different electron window from your application, and it will manage all the navigation returning the secrets as part of a promise. Due that this library does not even have electron as a dependency.

I might can give ideas for security as part of documentation if you think is valuable.

**Comment by AlexCatch** [comment]
I think the issue is that it almost encourages storing the private token in the bundle, this is a huge security concern as it takes all of 10 minutes to get the secret key.

The only safe option is explicitly allowing only the implicit grant flow or simply providing the code for the developer to send off to their own server for exchange to an access & refresh token.

**Comment by alvarolorentedev** [comment]
If you dont mind let me express why i dont feel those are options:
- Grant flow: you will have to store the credentials for a user, meaning that thare is the same issue. The difference is, with code you will need to invalidate token if you think it has been leaked. With implicit grant the user must change credentials.
- Server based: not really feasable for desktop apps with no backend (ex. git clients).

The Authorization code workflow was created to bound the issue of leaked credentials of a user in OAuth. The attack surface to the app is actually small, and don't endanger the real credentials of the user, or  all user as server-to-server flows.
For me the issue is not the flow used, but how are the tokens stored. In that case you can actually reduce the attack vector by:
- using something like node-keytar ( https://atom.github.io/node-keytar/ ) to delegate security to the os.
- Using some kind of encryption locally ( this will not make it more safe just more dificult to obtain)

sincerily my opinion is node/electron apps should relly on the os to store sensitive data the same as the rest of desktop apps.

**Comment by aguynamedben** [comment]
I haven't dug into the code of this library, but I'm also concerned that this repo could encourage the insecure practice of distributing OAuth key/secrets within an Electron app.

* Many users of the library will simply copy/paste code in the README
* Then they'll replace the values for `key` and `secret` with production values
* Then they'll distribute the app

The problem here is that anybody can use [asar](https://github.com/electron/asar) to unpackage your app in 1 minutes and easily find your key/secret. We've had multiple people do this with our app to snoop around. It happens... it's just too easy... it takes 2 minutes to unasar. A malicious user can and *will* grab your OAuth key/secret and try stuff. The upstream OAuth provider will think it's your app making the calls. Any calls made using your app's key/secret will appear to be you. It's possible your app's OAuth access becomes revoked by the upstream provider due to activity your app isn't performing. A malicious app could also access user data using your app's credentials and mishandle it.

For my app, we worried that malicious code would get our OAuth access shut down from upstream services. Or worse, create data security liabilities that point back to us.

@kanekotic if you want me to provide a proof-of-concept for why this is a problem, point me to your app and I'll check it out and message you privately. If you're storing OAuth keys/secrets in your app, it's going to be a problem.

I think keytar is a great solution for dynamically fetched accessTokens/refreshTokens, but not OAuth key/secrets that are shipped along with your app. Electron apps are extremely easily deconstructed.

If anything, there should be a massive warning in the README of this repo to explain this problem. Not just an easily copy/paste example.

Personally, anyone building an Electron app that needs to do OAuth should read [RFC 8252](https://tools.ietf.org/html/rfc8252) about 5 times. Have you read that? I'm not personally comfortable going anywhere off the rails of what RFC 8252 documents!

**Comment by aguynamedben** [comment]
The best way I know of:

* User needs to login to your site
* When the user wants to OAuth, they do it through your site. OAuth tokens/secrets for upstream services are stored server-side on your server.
* When OAuth is complete, the access/refresh tokens can be passed back to your app using the methods described in https://tools.ietf.org/html/rfc8252 or https://developers.google.com/identity/protocols/OAuth2InstalledApp (i.e. using 127.0.0.1, Option 2 in the Google documentation)

This keeps your sensitive keys/secrets protected on your server side, but allows the user to OAuth with them and pass the access/refresh tokens back to your Electron app.

That Google documentation is also required reading. Between that and REF 8252 it should become clear how to securely OAuth users with an easily decompilable native app (i.e. Electron).

**Comment by alvarolorentedev** [comment]
I think your main concern is Storage of key and secret of your app key and token, not user ones. Correct?

I will reiterate myself on that being part of the responsability of the electron application not the llibrary used for oauth, meaning is out of the concerns I have in my implementation of the library. 

If you have a backend your option is fully valid. But there are apps with no backends using for example social login. As explained there are other options if the app does not have this backend. 

The idea for node-keytar should be during installation provide already the keys of your app to the system. Rellying then in the OS and not on your code to store the keys (removing your concern on stored passwords on the code).

Again I will say I think this is something where each app needs to do their own threat modeling, and see wich is the best solution. Like allways there is no one size fits all.

**Comment by alvarolorentedev** [comment]
(closed because it does not reffer to an issue on the library, is a technical discussion)

**Comment by aguynamedben** [comment]
> during installation provide already the keys of your app to the system

How does this work on your app? Do you package the key/secret in you app's asar? The problem here isn't "where are key/secret stored?", it's "is anybody in the world able to access my app's OAuth key/secret and subsequently pretend to be my app?"

**Comment by aguynamedben** [comment]
At minimum I think the safest thing to do for the Electron community is to put some notes in the README around `key` and `secret` and point out the risk of packaging an app's OAuth key/secret in the asar. You're right, security is always specific to the app/code being written, but there's no reason to not document it. The current README will leave less security-inclined developers to package their key/secret.

Did you read RFC 8252 as I recommended? That's the current best practice for Electron+OAuth as far as I know.

**Comment by alvarolorentedev** [comment]
Sorry if I could not answer you before, I had a complex week. Let me try To clarify the subject:

## Problem Definition

Personally, **The concern** you expose **is part of a bigger one `secret management in desktop applications`**. 

Why:
- The Issue Is fully independent of electron or JS. It will happen in any other language that allow doing desktop or mobile applications. 
- The same issue appears for any other type of secrets or credentials an app may need (db credentials, aws/cloud ...).

I agree with you that if you have a backend you can use this as a cover for most of this process (I think I have repeated myself a few times on this). And seems sensible to follow that from the standard in this specific case. In the case this was the only way. Then what is the value of an electron app or any other desktop only app? more than just a shell for a web application?.

Nevertheless In a ton of cases this will not be the case and you are only interested in doing social login (oauth, basic, ...) to be able to interact with other systems.  Some examples from the top of my mind are:
- Video editing app that wants to upload videos to multiple platforms as youtube, vimeo, ...
- Social network management apps, that allow you to post into twitter, facebook, ...
- CI/CD build radiators...

This are apps that will require login capabilities to 3rd party systems, and do actually not require their own backend. So they do not fall on the target of what the standard and your solution is focused on. As the standard and your solution are related to owned services that use oauth.  

In any case we both agree `hardcoded` passwords is a bad practice. 

So what are possible solutions? 

## Solution ideas for apps with no backend

The starting point for me is for all the previously exposed cases. They do not need their own server side, so keys and secrets have to be distributed.

I still believe part of the solution should relay on the secret management storage of the OS. because the specific records should be only accessible by the application that installed them (and root users probably will end up having access to it, so that is why they should also not be plain text).

Lets explore the next workflow:
1. Secrets should be not held in the repo. 
2. CI/CD system should provide the keys or provide a retrieving capability to the installer creator process.
3. The installer (msi, exe, pkg, deb,...) should contain a phase of secret management. That is in charge of providing this keys to the os secret management system (I have never been talking about the asar).
4. The application should access the keys from the secure storage when required.

Also there are other steps to make your code more secureish:
- Obfuscation, in the case of js make sure all your code is minimized/uglified. so even if installation script is extracted is not straight forward understand it, same goes for the asar package.
- Encryption, making sure not to use plain text, as it will be really easy to understand.
- Do a checksum of your app before running to try to not allow tampering of your code. 

Again this does not make your key and secret secure. Just more difficult to obtain by attackers.

What other ideas can we come up with? 
are there vault systems that could be integrated?

## Conclusion 

Security is never a 100% on software systems. Even having them on a backend will not assure they wont be leaked, is just more complex. They only key that is safe Is the one that does is offline and never shared. The main intention of security is to make more difficult to intruders and attackers to have access to them.

Going back to the subject of this thread this is why I don't see a direct connection in between this package and the secret management issue, as they are in different levels of abstraction. If not any library that require a secret should then be flashing things in red. Is the user responsibility understand the specific security needs of their application.

Nevertheless I like the idea of giving guidelines on the things we agree in, so I will try to add a section about security. Specially with the things we agree like it is a bad practice to hardcode things on the code. I will also really appreciate if you come up with new ideas on how to improve security locally for non backend supported systems.

**Comment by AlexCatch** [comment]
@aguynamedben Thanks for the extensive input on this, I wasn't expecting it but you explained the issue a lot better than I ever could.

My only issue is that the package makes it easy & even makes it seem okay to be hardcoding secrets in your app, this package is essentially encouraging a dangerous implementation of OAuth in Electron apps in which OAuth was never designed to handle outside of the implicit grant flow.

There is a reason why some of the most popular Electron apps (GitKraken etc) use a socket method to handle OAuth - validation is handled through their site & the result is sent to the client through a socket.

It's just not secure & can be never secure to store secrets in client side code, which is essentially what we're arguing here.

This package is a very nice & well designed proof of concept but is not safe in the slightest to be used in production.

**Comment by aguynamedben** [comment]
>My only issue is that the package makes it easy & even makes it seem okay to be hardcoding secrets in your app, this package is essentially encouraging a dangerous implementation of OAuth in Electron apps

100%

I think I've registered my opinion here clearly enough, hopefully it helps somebody considering Electron security. If any readers of this are still in doubt, be sure you read https://tools.ietf.org/html/rfc8252
